### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [snurby7/project7#1]
It looks like the form inputs are resetting each time the form submits, while it's specified in the project criteria that `every form field should always show the current parameters`. [This example](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) may help you figure out how you can fix this problem.

Let me know when the code is updated and I'll take another look.

**Comment by snurby7** [comment]
e9290ceea6 fixes this issue, sorry about that, must have overlooked it.

**Comment by chrisvfritz** [comment]
:+1: Much better! This project looks fantastic now. :tada: 

This isn't something you have to change here, but one point of improvement is that you could avoid [the nested loops here](https://github.com/snurby7/project7/blob/master/views/holidays.erb#L27-L33) with [the `.flatten` method](http://apidock.com/ruby/Array/flatten). It's very useful when you have arrays within arrays and you just want a list of the objects at the end.

**Comment by snurby7** [comment]
That's version 2.0 :)
